[package]
name = "hashlife"
version = "0.0.0"
authors = ["Nicholas Buckeridge <bucknich@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.12"
termion = "1.5"
getrandom = "0.2"

[dev-dependencies]
itertools="0.9"

[[example]]
name = "demo"
path = "examples/demo.rs"
